//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddHandSlot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddHandSlot.ResourcesJson", typeof(ResourcesJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;BarColor&quot;:{&quot;a&quot;:1.0,&quot;b&quot;:0.278431385755539,&quot;g&quot;:0.431372582912445,&quot;r&quot;:0.694117665290833},&quot;BarHighlightColor&quot;:{&quot;a&quot;:1.0,&quot;b&quot;:0.0,&quot;g&quot;:0.728510022163391,&quot;r&quot;:1.0},&quot;BaseRatePerTick&quot;:0.0,&quot;BaseValue&quot;:4000.0,&quot;CannotBeInspected&quot;:false,&quot;DefaultStatusDescription&quot;:{&quot;DefaultText&quot;:&quot;&quot;,&quot;LocalizationKey&quot;:&quot;&quot;,&quot;ParentObjectID&quot;:&quot;&quot;},&quot;DefaultStatusIcon&quot;:{&quot;m_FileID&quot;:0,&quot;m_PathID&quot;:0},&quot;DefaultStatusIconWarpData&quot;:&quot;Weight&quot;,&quot;DefaultStatusIconWarpType&quot;:3,&quot;DefaultStatusName&quot;:{&quot;DefaultText&quot;:&quot;&quot;,&quot;LocalizationKey&quot;:&quot;&quot;,&quot;ParentObjectID&quot;:&quot;&quot;},&quot;Descri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EncumbranceLimitNum {
            get {
                return ResourceManager.GetString("EncumbranceLimitNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;BarColor&quot;:{&quot;a&quot;:1.0,&quot;b&quot;:0.278431385755539,&quot;g&quot;:0.431372582912445,&quot;r&quot;:0.694117665290833},&quot;BarHighlightColor&quot;:{&quot;a&quot;:1.0,&quot;b&quot;:0.0,&quot;g&quot;:0.728510022163391,&quot;r&quot;:1.0},&quot;BaseRatePerTick&quot;:0.0,&quot;BaseValue&quot;:6.0,&quot;CannotBeInspected&quot;:false,&quot;DefaultStatusDescription&quot;:{&quot;DefaultText&quot;:&quot;&quot;,&quot;LocalizationKey&quot;:&quot;&quot;,&quot;ParentObjectID&quot;:&quot;&quot;},&quot;DefaultStatusIcon&quot;:{&quot;m_FileID&quot;:0,&quot;m_PathID&quot;:0},&quot;DefaultStatusIconWarpData&quot;:&quot;Appetite&quot;,&quot;DefaultStatusIconWarpType&quot;:3,&quot;DefaultStatusName&quot;:{&quot;DefaultText&quot;:&quot;&quot;,&quot;LocalizationKey&quot;:&quot;&quot;,&quot;ParentObjectID&quot;:&quot;&quot;},&quot;Descrip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HandSlotNum {
            get {
                return ResourceManager.GetString("HandSlotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ActionModifiers&quot;:[],&quot;ActionObjectives&quot;:[],&quot;AddedCards&quot;:[],&quot;AddedStartingHours&quot;:0,&quot;CardsOnBoardObjectives&quot;:[],&quot;CheckingNotificationDetails&quot;:0,&quot;CompleteOnLose&quot;:false,&quot;CompleteOnWin&quot;:false,&quot;DifficultyRating&quot;:-10000,&quot;DisplayPriority&quot;:1000.0,&quot;EditorOnly&quot;:false,&quot;EquippedCards&quot;:[],&quot;HiddenUntilUnlocked&quot;:false,&quot;MoonsCost&quot;:0,&quot;NestedObjectives&quot;:[],&quot;NoSafetyMode&quot;:false,&quot;NotifyWhenNotChecked&quot;:false,&quot;OverrideEnvironment&quot;:{&quot;m_FileID&quot;:0,&quot;m_PathID&quot;:0},&quot;OverrideEquipment&quot;:false,&quot;OverrideWeather&quot;:{&quot;m_FileID&quot;:0,&quot;m_PathID&quot;:0} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pk_AddEncumbranceLimit {
            get {
                return ResourceManager.GetString("Pk_AddEncumbranceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ActionModifiers&quot;:[],&quot;ActionObjectives&quot;:[],&quot;AddedCards&quot;:[],&quot;AddedStartingHours&quot;:0,&quot;CardsOnBoardObjectives&quot;:[],&quot;CheckingNotificationDetails&quot;:0,&quot;CompleteOnLose&quot;:false,&quot;CompleteOnWin&quot;:false,&quot;DifficultyRating&quot;:-1000,&quot;DisplayPriority&quot;:1000.0,&quot;EditorOnly&quot;:false,&quot;EquippedCards&quot;:[],&quot;HiddenUntilUnlocked&quot;:false,&quot;MoonsCost&quot;:0,&quot;NestedObjectives&quot;:[],&quot;NoSafetyMode&quot;:false,&quot;NotifyWhenNotChecked&quot;:false,&quot;OverrideEnvironment&quot;:{&quot;m_FileID&quot;:0,&quot;m_PathID&quot;:0},&quot;OverrideEquipment&quot;:false,&quot;OverrideWeather&quot;:{&quot;m_FileID&quot;:0,&quot;m_PathID&quot;:0}, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pk_AddHandSlot {
            get {
                return ResourceManager.GetString("Pk_AddHandSlot", resourceCulture);
            }
        }
    }
}
